fpvandoorn/carleson

.gitignore

This PR remove `/.venv` from the `.gitignore` since it's unique to my setup and not generalisable. 
Sorry for the previous commit.

Remove `.venv` from `.gitignore`

---

blueprint/src/chapter/main.tex

Use capitalised clever references

---

blueprint/src/chapter/main.tex

This PR fixes the following error: 
> ERROR: Label '-Hardy-Littlewood' could not be resolved

Fix label error

---

blueprint/src/chapter/main.tex

This PR moves the abstract under `\maketitle` to display it correctly in the blueprint website.

Fix abstract location (blueprint web)

---

Carleson/DiscreteCarleson.lean

Otherwise, the statement is false when `q` is less than `1`. See [this](https://leanprover.zulipchat.com/#narrow/stream/442935-Carleson/topic/C2_0_2.20is.20positive.3F) Zulip discussion.

chore: add `ProofData` to `C2_0_2_pos`

---

Carleson/AntichainOperator.lean
Carleson/Defs.lean
Carleson/DiscreteCarleson.lean
Carleson/GridStructure.lean
Carleson/Psi.lean
Carleson/TileExistence.lean
blueprint/src/chapter/main.tex

This also removes all but one of the `exact_mod_cast`s left over from the naturalisation of `a, A, D, S`.

Lemma 2.1.2 and wiggle order lemmas

---

Carleson/DiscreteCarleson.lean
Carleson/GridStructure.lean
blueprint/src/chapter/main.tex

I had to add the property `coeGrid_measurable` of `GridStructure` in order to use `measure_biUnion_finset`, but this property is specified in the blueprint:
> A grid structure $(\mathcal{D}, c, s)$ on $X$ consists of a finite collection $\mathcal{D}$ of pairs $(I, k)$ of **Borel sets** in $X$...

Lemma 5.2.2

---

Carleson/AntichainOperator.lean
Carleson/Psi.lean
Carleson/ToMathlib/MeasureReal.lean
Carleson/ToMathlib/Misc.lean

I had to add assumptions (in particular, `IsCZKernel a K`) in a few theorems. There were also some places where the theorems included unnecessary assumptions (`hs : s ∈ Icc (-S : ℤ) S`), which I removed.
The blueprint says that `X` is a metric space, but the lean file made it a `PseudoMetricSpace` instead. I left it as a `PseudoMetricSpace` because this did not make the proofs substantially more difficult, but if desired `X` could be changed to a metric space to simplify the proofs a little bit.
The code is kind of slow. I tried to speed it up a bit, but someone with more experience might be able to do better.

Proof of Lemma 2.1.3 and the other results in Psi.lean

---

Carleson/DiscreteCarleson.lean
Carleson/FinitaryCarleson.lean

Prove `finitary_carleson` (Proposition 2.0.1).
Also clean up a few apparent typos:
* There were several instances of `Measurable G'` which I changed to `MeasurableSet G'`.
* I changed the definition of `C2_0_1` so that it's defined to be equal to `C2_0_2`. (The constants in the blueprint are not equal, but this appears to be a typo.)
* I changed the definition of `C2_0_2` from `C5_1_2 a q + C5_1_2 a q` to `C5_1_2 a q + C5_1_3 a q`.
* I changed `1/q` in the statement of `finitary_carleson` to `q⁻¹` for consistency with `discrete_carleson`.

Proposition 2.0.1

---

Carleson/Psi.lean
blueprint/src/chapter/main.tex

Correct the blueprint's proof of equation (2.1.4) in Lemma 2.1.3. 
Also perform some minor cleanup of Psi.lean.

Correct blueprint proof of Lemma 2.1.3

---

Carleson/Defs.lean
Carleson/FinitaryCarleson.lean
Carleson/Psi.lean

Prove `integrable_tile_sum_operator`.
As an intermediate step, prove that `y ↦ Ks s x y` is integrable.

Prove integrable_tile_sum_operator

---

Carleson/FinitaryCarleson.lean
Carleson/GridStructure.lean
Carleson/TileStructure.lean

Correct a typo in the definition of `T` in TileStructure.lean.
Prove `tile_sum_operator`. There's one `sorry` left in the proof, which according to the blueprint should follow easily from the fact that the ranges of `σ₁` and `σ₂` are contained in [-S, S]. But unless I'm missing something, that fact isn't in the code yet.

Prove tile_sum_operator

---

Carleson/Defs.lean
Carleson/FinitaryCarleson.lean

Prove the lemma that I was previously calling `Icc_subset`. (I hadn't noticed that the `S` in FinitaryCarleson.lean was notation for `S X`.)
Rename the lemma `Icc_σ_subset_Icc_S` and move it to Defs.lean, alongside related lemmas.

Prove Icc_subset

---

Carleson/DiscreteCarleson.lean
Carleson/HardyLittlewood.lean
blueprint/src/chapter/main.tex

Prove Lemma 5.2.1.
Notes: 
* I changed the definition of `highDensityTiles` to use a strict inequality. I think this was a typo in the blueprint, since everything else seems consistent with a strict inequality. I also updated the definition in the blueprint.
* The proof in the blueprint had an extra factor of 2, so the Lemma 5.2.1 that I proved is stronger by a factor of 2. I also updated the statement and proof in the blueprint.
* I changed the statement of `measure_biUnion_le_lintegral` to use `ℝ≥0∞` rather than `ℝ≥0`. This was only to avoid some annoying casting; none of the numbers involved in the proof are infinite, so the `ℝ≥0` version should theoretically be adequate. If the `ℝ≥0∞` version turns out to be substantially harder to prove, it should be possible to change back to the …

Prove Lemma 5.2.1

---

.github/workflows/push.yml

This PR ensures correct docs caching and minimization of disk space usage

Speed up CI 

---

blueprint/src/chapter/main.tex

this PR adds missing `\leanok` and `\lean{}` tags to the blueprint for all lemmas in 4.1, completing the section.

add lean tags for remainder of 4.1 in blueprint

---

Carleson/WeakType.lean

Prove the lemmas about `wnorm` and `MemWℒp` in WeakType.lean.
`HasStrongType.hasWeakType` was originally stated with the assumption `(hp : 1 ≤ p)`, which needed to be changed to `(hp' : 1 ≤ p')`.
I also corrected very minor typos in the documentation of `HasWeakType` and `HasStrongType`.

Prove lemmas about wnorm

---

Carleson/DiscreteCarleson.lean
Carleson/Forest.lean
Carleson/TileStructure.lean
blueprint/src/chapter/main.tex

Prove Lemma 5.2.8.
Notes:
* I changed the statement of Lemma 5.2.8 to use `ℝ` instead of `ℕ`, and changed the exponent `9 * a - j` to use subtraction in  `ℤ` instead of `ℕ`. I think the lemma is only used to prove an inequality in `ℝ≥0`, so this shouldn't cause any problems.
* I corrected a minor error in the blueprint's proof, where it referred to `u` and `u'` as possible elements of `B'`, rather than `𝒬 u` and `𝒬 u'` (and then needed an extra injectivity argument to finish the proof).

Prove Lemma 5.2.8

---

.github/workflows/push.yml
.github/workflows/push_pr.yml

- Solved all warnings 
- Disk space usage seems to be reduced significantly (from 357 MB to just 19 MB), but I think it's nothing but a change in the variable displayed (from uncompressed to compressed size)

Bump GitHub actions

---

Carleson/Defs.lean
Carleson/DiscreteCarleson.lean
Carleson/Forest.lean
Carleson/GridStructure.lean
Carleson/HardyLittlewood.lean
Carleson/ToMathlib/Misc.lean
blueprint/src/chapter/main.tex

For the discussion on why `BorelSpace X` is needed in `HardyLittlewood.lean` see https://leanprover.zulipchat.com/#narrow/stream/442935-Carleson/topic/How.20to.20prove.20a.20ball.20is.20measurable/near/455002668

Lemma 5.2.10, Task 58

---

Carleson/HardyLittlewood.lean
Carleson/RealInterpolation.lean
Carleson/ToMathlib/Misc.lean

- The definition of `SublinearOn` was missing the requirement `c ≥ 0`.
- The statement of `MeasureTheory.SublinearOn.maximalFunction` had a spurious `p`; `MB` is defined with p=1, so there's no need for a general `p`.
- The blueprint says that `𝓑` is finite, so I used that assumption even though several theorems in the file assume `𝓑` is countable instead. I also changed the assumption in `hasStrongType_MB`.

Prove MeasureTheory.SublinearOn.maximalFunction

---

Carleson/HardyLittlewood.lean

Partial proofs of `Set.Countable.measure_biUnion_le_lintegral` and `HasWeakType.MB_one`
- The proof of `Finset.measure_biUnion_le_lintegral` has one `sorry` left because the version of the Vitali covering lemma that we have uses closed balls, but we need a statement about open balls. This could be fixed using a different version of Vitali, or adding an assumption about the metric space `X`. For example, it would be adequate if we knew that `interior ∘ closedBall = ball` in `X`.
- The proof of `HasWeakType.MB_one` needs a statement about the boundedness of the radii in `𝓑`. Of course this is trivial if `𝓑` is assumed to be finite, but I don't see how to handle it for countable `𝓑`.

Set.Countable.measure_biUnion_le_lintegral and HasWeakType.MB_one

---

CONTRIBUTING.md
Carleson/AntichainOperator.lean
Carleson/Classical/CarlesonOnTheRealLine.lean
Carleson/Classical/CarlesonOperatorReal.lean
Carleson/Classical/ClassicalCarleson.lean
Carleson/Classical/ControlApproximationEffect.lean
Carleson/Classical/DirichletKernel.lean
Carleson/Classical/Helper.lean
Carleson/Classical/HilbertKernel.lean
Carleson/Classical/VanDerCorput.lean
Carleson/ForestOperator.lean
Carleson/RealInterpolation.lean
Carleson/ToMathlib/Misc.lean
Carleson/WeakType.lean
blueprint/src/chapter/main.tex

* Open namespace `MeasureTheory` in various places
* Add `\leanok` to statements of section 7.1

some cleanup

---

Carleson/Classical/ControlApproximationEffect.lean
Carleson/HardyLittlewood.lean
Carleson/Psi.lean
Carleson/RealInterpolation.lean

- compress some apply/exact statements when a clear win
- use fun_prop and positivity more
- (twice) extract an auxiliary lemma from an argument
- remove some `have`s which are used at most once or twice
- use .le instead of le_of_lt
- remove one adaptation note which is now obsolete
- use dot notation more

Miscellaneous golfs, mostly to RealInterpolation.lean

---

Carleson/Discrete/ExceptionalSet.lean
Carleson/ForestOperator.lean
Carleson/GridStructure.lean
blueprint/src/chapter/main.tex

There is an error in the blueprint proof of 7.1.5: it is possible that the minimum $s_1$ of $\sigma(\mathfrak u,x)$ is equal to $S$, and in that case the equation to be shown reduces to
```
∑ x_1 ∈ t.σ u x, ∫ (y : X), Ks x_1 x y * approxOnCube (𝓙 (t.𝔗 u)) f y = 0
```
which is clearly false in general. (In fact it can be easily reduced further to `∫ (y : X), Ks S x y * approxOnCube (𝓙 (t.𝔗 u)) f y = 0`, but this is not in the PR code.)

Lemma 7.1.1, 7.1.2 and most of 7.1.5

---

Carleson/Defs.lean
Carleson/ForestOperator.lean
Carleson/GridStructure.lean
Carleson/TileExistence.lean
Carleson/ToMathlib/Misc.lean
blueprint/src/chapter/main.tex

…and along the way tweak the definition of `upperRadius` to be `ENNReal`-valued, to accommodate the possibility of the relevant set being unbounded.

Finish the proof of Lemma 7.1.5 + Lemma 7.4.7

---

scripts/update_mathlib.bat
scripts/update_mathlib.sh

Mathlib currently fetches the cache as part of [its post-update hook](https://github.com/leanprover-community/mathlib4/blob/ede775853cc9f271a9fcf1475dec887f82544e30/lakefile.lean#L166-L176). Thus, calling `lake exe cache get` after a mathlib update is unnecessary.

Remove unnecessary step in update_mathlib scripts

---

Carleson/HolderVanDerCorput.lean
blueprint/src/chapter/main.tex

- adjust order (tR instead of Rt) in the blueprint, for consistency
- improve LaTeX indentation a bit
- make  NNReal-valued instead; fix a typo in its doc-string

chore: small clean-ups in the Hölder-van der Corput file

---

.github/workflows/create-release.yml

Adds a `create-release` workflow which automates the creation of a new Git tag and GitHub release when the `lean-toolchain` file is updated in the `main` branch.

Add `create-release` workflow

---

.github/workflows/push_pr.yml
lakefile.toml

And disable the 'long lines check' in CI, as it doesn't seem to work. The corresponding mathlib linter finds *many* violations. If desired, it seems easier to just enable that linter instead.

chore: enable two uncontroversial mathlib linters

---

Carleson/FinitaryCarleson.lean
Carleson/ForestOperator/RemainingTiles.lean
Carleson/GridStructure.lean
Carleson/RealInterpolation.lean
Carleson/TileExistence.lean

I intend to revisit these; now, one can at least find them somewhat easily.

chore: label sorries from bumping to 4.13.0

---

Carleson/Antichain/AntichainOperator.lean
Carleson/Classical/Approximation.lean
Carleson/Classical/Basic.lean
Carleson/Classical/CarlesonOnTheRealLine.lean
Carleson/Classical/CarlesonOperatorReal.lean
Carleson/Classical/ClassicalCarleson.lean
Carleson/Classical/ControlApproximationEffect.lean
Carleson/Classical/DirichletKernel.lean
Carleson/Classical/Helper.lean
Carleson/Classical/HilbertKernel.lean
Carleson/Classical/VanDerCorput.lean
Carleson/CoverByBalls.lean
Carleson/DoublingMeasure.lean
Carleson/ForestOperator/LargeSeparation.lean
Carleson/ForestOperator/RemainingTiles.lean
Carleson/Psi.lean
Carleson/RealInterpolation.lean
Carleson/TileExistence.lean
Carleson/ToMathlib/Height.lean
Carleson/WeakType.lean
lakefile.toml

Both of them could help making proofs more robust. For code to be upstreamed, fixing these is required anyway.

chore: enable the flexible and multi-goal linters

---

Carleson/HolderVanDerCorput.lean

- tweak statement of `cutoff_Lipschitz`
- add constant `n` from equation `8.0.7`
- prove `support_holderApprox_subset`
Extracted from #160.

chore: further progress towards lemma 8.0.1

---

Carleson/Antichain/AntichainTileCount.lean
Carleson/ForestOperator/AlmostOrthogonality.lean
Carleson/ForestOperator/Forests.lean
Carleson/ForestOperator/L2Estimate.lean
Carleson/ForestOperator/LargeSeparation.lean
Carleson/ForestOperator/PointwiseEstimate.lean
Carleson/ForestOperator/QuantativeEstimate.lean
Carleson/Psi.lean
Carleson/TileStructure.lean
Carleson/ToMathlib/BoundedCompactSupport.lean
Carleson/ToMathlib/Misc.lean
blueprint/src/chapter/main.tex

This proves Lemma 7.4.2 and various prerequisites that will also be useful for other lemmas. 
Main additions are:
In `ForestOperator/AlmostOrthogonality.lean`:
- `adjoint_tree_estimate`: Lemma 7.4.2
- `adjointCarleson_adjoint`: `adjointCarleson` is actually the adjoint of `carlesonOn`
- `BoundedCompactSupport.adjointCarleson`: `adjointCarleson` has bounded compact support if the input function does
In `TileStructure.lean`:
- `AEStronglyMeasurable.carlesonOn`: `carlesonOn` is a.e. strongly measurable
- `BoundedCompactSupport.carlesonOn`: `carlesonOn` has bounded compact support if the input function does
In `Psi.lean`:
- `exists_bound_of_norm_Ks`: existence of uniform bound for `‖Ks x y‖` if `x` is in a bounded set
The new file `BoundedCompactSupport.lean` defines a predicate for functions …

Lemma 7.4.2, `adjointCarleson_adjoint`, `BoundedCompactSupport`

---

.devcontainer/devcontainer.json
README.md

My laptop died, so setting up codespaces for myself 😅 
- fixes a typo in `devcontainer.json`, which makes github codespaces work.
- updates `README.md` to indicate contributors can use github codespaces.

Infrastructure - set up github codespaces

---

Carleson/Defs.lean
Carleson/ForestOperator/PointwiseEstimate.lean
Carleson/Psi.lean
blueprint/src/chapter/main.tex

Prove Lemma 7.1.3, and correct a minor error in the blueprint proof.

Lemma 7.1.3

---

Carleson/ForestOperator/AlmostOrthogonality.lean
Carleson/HardyLittlewood.lean
Carleson/RealInterpolation.lean
Carleson/ToMathlib/ENorm.lean
Carleson/ToMathlib/Misc.lean
Carleson/WeakType.lean

* Start using some classes that bundle `ENorm` with some algebra/topology. This ensures that these results can be used for `ENNReal`, and allows us to remove a bunch of `|>.toReal` in statements and some `Real`-`ENNReal`-juggling.
* Generalize `HasWeakType` and friends to `ENorm`
* Partially generalize `RealInterpolation` to `ENorm` (requires further investigation and Mathlib generalizations)
* Let `A : ℝ≥0∞` or `A : ℝ≥0` in `RealInterpolation`.
* Generalize the fact that the Hardy-Littlewood maximal function has strong type to countable families of balls
* Still a change of the proof is needed for `hasStrongType_globalMaximalFunction`

Use `ENorm` in WeakType and HardyLittlewood

---

Carleson/Defs.lean
Carleson/MetricCarleson.lean

The definition of `PreProofData.hasBoundedStrongType_Tstar` said that `(nontangentialOperator K · · |>.toReal)` has bounded strong type, but I think the `toReal` is a mistake; with the `toReal` present, a case where the nontangential operator is ∞ everywhere would qualify as bounded strong type.

Fix definition of PreProofData.hasBoundedStrongType_Tstar

---

lakefile.toml

[Zulip](https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/lake.20doesn't.20find.20option)
This allows project files that do not import the flexible linter to pass CI.

fix: use `weak` flexible linter option

---

Carleson/Forest.lean
Carleson/ForestOperator/LargeSeparation.lean
Carleson/ForestOperator/RemainingTiles.lean

This PR adds `s p ≤ s u` result to the `Forest.if_descendant_then_subset` lemma as discussed [here](https://leanprover.zulipchat.com/#narrow/channel/442935-Carleson/topic/lemma.207.2E7.2E4).

Lemma Forest.𝓘_le_𝓘

---

Carleson/Antichain/AntichainOperator.lean
Carleson/Classical/CarlesonOnTheRealLine.lean
Carleson/Defs.lean
Carleson/Psi.lean
Carleson/ToMathlib/Data/ENNReal.lean
Carleson/TwoSidedCarleson/MainTheorem.lean

* Define `vol` in the root namespace that lives in `ENNReal`. `Real.vol` is still available.
* put `C_K` in `NNReal`
* prove `ENNReal`-versions of the `IsOneSidedKernel`-axioms. Replace the axiom in `IsTwoSidedKernel` with its `ENNReal` version. (Doing that for `IsOneSidedKernel` is a todo.)
* Prove `ENNReal` version of `kernel_bound`. (The old version is `kernel_bound_old`.)

define vol in ENNReal

---

Carleson/ToMathlib/MeasureTheory/Integral/SetIntegral.lean

The new proof can be simplified to avoid some back-and-forth, but compiles.
I found this in an old branch of mine: should we simply land this, or clean it up further first?

chore: port one ennnorm theorem to enorm

---

Carleson/Classical/HilbertStrongType.lean
blueprint/src/chapter/main.tex

align the blueprint proof with the Lean proof (which could use some facts that were already in Mathlib).
Remove some blueprint lemmas now unused in the new proof.
Add a `\leanok`.

proof of spectral_projection_bound in blueprint

---

Carleson/ToMathlib/HardyLittlewood.lean
Carleson/ToMathlib/WeakType.lean

Clean-ups on top of #275: remove unintentional changes, align style more with mathlib and clean up the variable blocks. Now, each theorem only asks for the minimal necessary typeclass assumptions, and it is clear which theorems require normed spaces and which ones don't.
All in all, #275 and this PR together
- correct the statement of HasWeakType.const_mul (which only holds for `p' ≠ 0`)
- completes the proof of `HasWeakType.const_mul`
- weaken the hypotheses in this file: many lemmas only require `[MulActionWithZero 𝕜 E] [IsBoundedSMul 𝕜 E]` and not `[NormedSpace 𝕜 E]`

chore: clean up #275

---

Carleson/ToMathlib/RealInterpolation.lean

- Rename aestronglyMeasurable_trunc{Compl} to AEStronglyMeasurable.trunc{Compl}.
This enables dot notation (and matches their content). Do the same for three more lemmas not in #209.
- Golf the proof of .truncCompl.
Extracted from/inspired by #209; reducing the diff in MR-cleanup-realinterpolation2.

chore(RealInterpolation): small golfs

---

lakefile.toml

This is cargo-culted by matching [mathlib4/#23667](https://github.com/leanprover-community/mathlib4/pull/23667).

chore(lakefile.toml): remove moreLeanArgs

---

Carleson/ToMathlib/ENorm.lean

Somehow, the git history in #283 became too confusing: let's land these helper lemmas separately, which are clearly good and necessary. Also note that two lemmas have already been upstreamed.

chore: further enorm lemmas

---

Carleson/ToMathlib/RealInterpolation.lean

This matches mathlib style, and allows `rw?` to work better.

chore(RealInterpolation): use < for inequalities

---

Carleson/ToMathlib/HardyLittlewood.lean
Carleson/ToMathlib/WeakType.lean

One section about the layercake formula remains (and will be changed in a future PR). This requires generalising a handful of mathlib lemmas: https://github.com/leanprover-community/mathlib4/pull/23707 contained some of these, others need ENormedSpace to be in mathlib first.
For most of this file, there is a trade-off about generality to be made: currently, there is no typeclass unifying both a normed space over a field and an ENormedSpace. Hence, we usually add enorm variants of existing lemmas and keep the existing versions.
We make one change, though: the normed space becomes primed; the enorm version stays unprimed.

feat(WeakType): generalise most remaining lemmas to enorm

---

Carleson/ToMathlib/HardyLittlewood.lean
Carleson/ToMathlib/Misc.lean
Carleson/TwoSidedCarleson/Basic.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean
blueprint/src/chapter/main.tex

Update:
* Now also includes the F2 estimate
* I think `HasBoundedWeakType` should be refactored to use `BoundedFiniteSupport` instead of three separate conditions. If desired I can make a separate PR for that after this lands.
The below has already been addressed.
<strike>Some points of attention:
* This lemma will need `globalMaximalFunction_lt_top` from `HardyLittlewood.lean : 710` but don't know how to do that. Marked with two sorries at `L707`, `L710`
* To prove `czOperator_aemeasurable` (or similar) at `L671` I was stuck with dealing with functions defined as integrals. Probably a matter of me not knowing the right Mathlib results. Or is this where `hT` is actually put to use?
* In applying some `indicator` results (`L720`), I encountered "deterministic timeout" errors, with Lean …

Lemma 10.1.4 (both parts)

---

Carleson/ToMathlib/HardyLittlewood.lean

Proof of the lower-semicontinuity of the maximal function and lower-semicontinuity of the global maximal function.
Although not used in the proof, I also proved `continuous_average_ball` under an extra assumption. Without that assumption I proved `lowerSemicontinuous_integral_ball`. I'm not sure these are still useful, because they are currently not used. Feel free to discard.

Lower-semicontinuity of maximal function - Task 135

---

Carleson/Antichain/TileCorrelation.lean
Carleson/Psi.lean
Carleson/TileExistence.lean
Carleson/ToMathlib/HardyLittlewood.lean
Carleson/ToMathlib/WeakType.lean
blueprint/src/chapter/main.tex

After filling in a sorry and tidying up a bit I have checked using `#print axioms` that each of the five Lean statements corresponding to Proposition 2.0.6 – as well as `row_correlation` – depends only on `[propext, Classical.choice, Quot.sound]`.

Mark Hardy–Littlewood as finished

---

Carleson/Classical/Basic.lean
Carleson/Classical/DirichletKernel.lean
Carleson/Classical/HilbertStrongType.lean
Carleson/ToMathlib/Misc.lean
Carleson/ToMathlib/Topology/Instances/AddCircle/Defs.lean
blueprint/src/chapter/main.tex

I had to change a little bit the blueprint and the Lean statements, as the original proof was only correct up to sign: in the proof of Lemma 11.3.5, one wants to approximate a function kappa of the form .../(1 - e^{i x}), but the proof pretends that it's .../(1 - e^{-ix}) instead, see (11.3.24). In the PR, I change the definition of the approximate Hilbert transform (11.3.2), replacing M_{-n-N} S_{n+N} M_{n+N} with M_{n+N} S_{n+N} M_{-n-N} to make sure that what comes out is indeed .../(1 - e^{ix}). With this modified approximate Hilbert transform, everything seems to work fine.

feat: proof of Lemma 11.3.5

---

Carleson/Defs.lean
Carleson/Discrete/MainTheorem.lean
Carleson/FinitaryCarleson.lean
Carleson/MetricCarleson/Truncation.lean
Carleson/TwoSidedCarleson/MainTheorem.lean
blueprint/src/chapter/main.tex

Including the `discrete_carleson`, `finitary_carleson` and `two_sided_metric_carleson` constants that were never quite corrected after bumps.
Also remove `volume_F_pos` and `volume_G_pos` since 1.0.2 is completed and none of #452 (11.1.6), #438 (6.1.3) or #449 (7.7.2) use those assumptions.

Change `471a^3+4` to `472a^3`

---

Carleson.lean
Carleson/Defs.lean
Carleson/MetricCarleson/Basic.lean
Carleson/ToMathlib/MeasureTheory/Function/LpSeminorm/Basic.lean
Carleson/ToMathlib/MeasureTheory/Integral/IntegrableOn.lean
Carleson/ToMathlib/Misc.lean
Carleson/TwoSidedCarleson/Basic.lean
Carleson/TwoSidedCarleson/MainTheorem.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean
Carleson/TwoSidedCarleson/WeakCalderonZygmund.lean

The TwoSidedCarleson folder still contained a number of general results that were supposed to go in ToMathlib.
This PR addresses that and other minor fixes.
The MetricCarleson folder was also checked with only minor changes.
I was not sure where to put `iSup_rpow` so I put it in Misc.

Cleanup TwoSidedCarleson / MetricCarleson folders

---

.github/workflows/push.yml

This update fixes the bug where Mathlib (and some other dependency) docs were not found in the cache. This should bring back build times down to the usual values.

chore(deps): Update docgen-action
