blueprint/src/print.tex

Fix fontspec error

---

blueprint/src/chapter/main.tex

Add missing `\lean{}` and fix formatting

---

Carleson/CoverByBalls.lean
Carleson/Defs.lean

Note that my proof of 2.1.1 fuses ` Θ.mk_le_of_le_dist` and ` Θ.finite_of_le_dist`.

2.1.1 and `CoveredByBalls.trans`

---

Carleson/Defs.lean
Carleson/DoublingMeasure.lean
Carleson/GridStructure.lean
Carleson/TileExistence.lean

this pr includes proofs of 4.1.1 and 4.1.2. 
it changes the requirements for `DoublingMeasure`, making the constant `NNReal`-valued.
this pr does not include changes to the blueprint. guidance on how to appropriately change it is welcome.
this pr also adds some auxilary lemmas about `DoublingMeasure`.

finished 4.1.1 and 4.1.2

---

Carleson/Theorem1_1/Basic.lean
Carleson/Theorem1_1/Dirichlet_kernel.lean
Carleson/Theorem1_1/Hilbert_kernel.lean
Carleson/TileExistence.lean

This PR simplifies and optimises a few proofs.

Golf a few proofs

---

Carleson/WeakType.lean

Task 15: Fill in proofs in first part of `WeakType.lean`

Add first version of proofs for task 15

---

Carleson/DiscreteCarleson.lean
Carleson/GridStructure.lean
Carleson/TileExistence.lean
Carleson/TileStructure.lean
blueprint/src/chapter/main.tex

Also extract a common proof motif in `GridStructure`.

Lemmas 5.2.3, 5.2.4, 5.3.4

---

.github/workflows/push.yml

Fix disk space issue 

---

Carleson/Defs.lean
Carleson/TileExistence.lean
blueprint/src/chapter/main.tex

Definition of `𝓩` and its properties

---

blueprint/src/chapter/main.tex

Fix some constants in Lemma 6.1.3.

Fix constants in blueprint

---

Carleson/RealInterpolation.lean

chore(RealInterpolationTheorem): misc golfs

---

CONTRIBUTING.md
Carleson/Classical/Approximation.lean
Carleson/Classical/Basic.lean
Carleson/Classical/CarlesonOnTheRealLine.lean
Carleson/Classical/ClassicalCarleson.lean
Carleson/Classical/ControlApproximationEffect.lean
Carleson/Classical/DirichletKernel.lean
Carleson/Classical/HilbertKernel.lean
Carleson/Classical/VanDerCorput.lean
Carleson/Discrete/Defs.lean
Carleson/Discrete/ExceptionalSet.lean
Carleson/Discrete/Forests.lean
Carleson/FinitaryCarleson.lean
Carleson/Forest.lean
Carleson/ForestOperator.lean
Carleson/GridStructure.lean
blueprint/src/chapter/main.tex

* Cleanup some imports
* Cleanup some `Real.pi`
* Use notation for `Finset.univ.filter`
* State lemmas in Section 7.2

Cleanup and Section 7.2

---

CONTRIBUTING.md
Carleson/Classical/ClassicalCarleson.lean
Carleson/Discrete/Defs.lean
Carleson/Discrete/Forests.lean
Carleson/FinitaryCarleson.lean
Carleson/Forest.lean
Carleson/ForestOperator.lean
Carleson/HardyLittlewood.lean
Carleson/TileStructure.lean
blueprint/src/chapter/main.tex

Also:
* Use the simpler statement of classical Carleson as the main theorem
* Move `stackSize`

State lemmas in chapter 7

---

Carleson/AntichainOperator.lean
Carleson/Defs.lean
Carleson/DoublingMeasure.lean
Carleson/ForestOperator/L2Estimate.lean
Carleson/HardyLittlewood.lean
Carleson/RealInterpolation.lean
Carleson/TileExistence.lean

golf: use gcongr and positivity more 

---

Carleson/ForestOperator/LargeSeparation.lean
blueprint/src/chapter/main.tex

The proof is ready, PR review is appreciated.

Lemma 7.5.8 (scales impacting interval)

---

Carleson/Classical/ControlApproximationEffect.lean
Carleson/Classical/DirichletKernel.lean

and one minor golf I spotted while in the area. One measurability proof took about 10 seconds before, but is nearly instant with fun_prop.
Depends on #165.

chore: use fun_prop more

---

Carleson/HolderVanDerCorput.lean

feat: progress towards lemma 8.0.1

---

Carleson/GridStructure.lean

See zulip discussion [here](https://leanprover.zulipchat.com/#narrow/channel/442935-Carleson/topic/.E2.9C.94.20Finiteness.20of.20.60I.20u.60.20in.205.2E2.2E9)

feat: add volume_coeGrid_lt_top to finiteness aesop rule set

---

Carleson/Discrete/ExceptionalSet.lean

Lemma 5.2.9
Co-authored-by: Julian Berman <Julian@GrayVines.com>
Co-authored-by: Aaron Hill <aa1ronham@gmail.com>
Co-authored-by: Eric Paul <eric.1334@icloud.com>

feat: lemma 5.2.9

---

Carleson/ForestOperator/LargeSeparation.lean
Carleson/GridStructure.lean
blueprint/src/chapter/main.tex

[[blueprint]](https://florisvandoorn.com/carleson/blueprint/treesection.html#moderate-scale-change)
This is ready, PR review is appreciated.

Lemma 7.5.3

---

Carleson/ForestOperator/RemainingTiles.lean
Carleson/ToMathlib/BoundedCompactSupport.lean
Carleson/ToMathlib/Misc.lean
blueprint/src/chapter/main.tex

In this PR:
- some content in helper file `BoundedCompactSupport`, mainly `prod_mul`; meant towards making this file more useful
- proof of Lemma 7.6.1 (very similar to Lemma 7.5.1 by @lakesare)
The proofs of Lemma 7.5.1/7.6.1 could be unified/simplified, but it may not be worth the effort at this point.

Lemma 7.6.1, `BoundedCompactSupport.prod_mul`

---

Carleson/HolderVanDerCorput.lean
blueprint/src/chapter/main.tex

Proves equation (8.0.8), except for one sorry --- which is progress towards Lemma 8.0.1. All of this is entirely my code.
The next PR will complete the proof of that lemma, using `sgouezel`'s work.

feat: equation (8.0.8)

---

Carleson.lean
Carleson/Classical/CarlesonOnTheRealLine.lean
Carleson/Classical/HilbertStrongType.lean
Carleson/ToMathlib/WeakType.lean
Carleson/TwoSidedCarleson/MainTheorem.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean
Carleson/TwoSidedCarleson/WeakCalderonZygmund.lean
Carleson/TwoSidedMetricCarleson.lean

also formulate Lemma 10.2.1 and reformulate some other lemma statements.

split chapter 10 file

---

Carleson/ToMathlib/Analysis/Convex/SpecificFunctions/Basic.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean

~~Currently proved relative to `(4 * (1 - 2 ^ (-1 / 4 : ℝ)))⁻¹ ≤ (2 : ℝ)`~~
Ok proof is done now, though could still be cleaned up.

Lemma 10.1.1

---

Carleson/Antichain/AntichainTileCount.lean
Carleson/Classical/Approximation.lean
Carleson/Classical/Basic.lean
Carleson/Classical/CarlesonOperatorReal.lean
Carleson/Classical/DirichletKernel.lean
Carleson/Classical/VanDerCorput.lean
Carleson/ForestOperator/L2Estimate.lean
Carleson/Psi.lean
Carleson/ToMathlib/ENorm.lean
Carleson/ToMathlib/HardyLittlewood.lean

Some tweaks salvaged from #229, and some small performance improvements I found.

chore/perf: miscellaneous small tweaks

---

Carleson/ForestOperator/Forests.lean
Carleson/GridStructure.lean
Carleson/TileStructure.lean
Carleson/ToMathlib/Data/Set/Lattice.lean
Carleson/ToMathlib/Order/Chain.lean

Adds definition body and proofs for lemma 7.7.1

Row decomposition 7.7.1

---

Carleson/Calculations.lean
Carleson/Forest.lean
Carleson/ForestOperator/Forests.lean
Carleson/TileStructure.lean

this PR completes the proof of lemma 7.7.4

lemma 7.7.4 disjoint row support

---

Carleson/ForestOperator/LargeSeparation.lean
Carleson/ForestOperator/RemainingTiles.lean
Carleson/ToMathlib/Data/NNReal.lean
Carleson/ToMathlib/DoublingMeasure.lean
Carleson/ToMathlib/Misc.lean
blueprint/src/chapter/main.tex

@lakesare used the wrong disjointness assumption in `moderate_scale_change`, so this has been fixed too.

Lemma 7.5.2 and 7.6.3

---

Carleson/Antichain/AntichainTileCount.lean
Carleson/Calculations.lean
Carleson/Classical/Helper.lean
Carleson/Defs.lean
Carleson/ForestOperator/Forests.lean
Carleson/ForestOperator/PointwiseEstimate.lean
Carleson/ForestOperator/RemainingTiles.lean
Carleson/Psi.lean
Carleson/TileExistence.lean
Carleson/ToMathlib/Analysis/Convolution.lean
Carleson/ToMathlib/BoundedCompactSupport.lean
Carleson/ToMathlib/BoundedFiniteSupport.lean
Carleson/ToMathlib/MeasureReal.lean

as it's already contained in the `MemLp` assumption.
Also, I ran the linter on the project, and fixed a few of the things it mentioned.

drop the `aestronglyMeasurable` field in `BoundedFiniteSupport`

---

Carleson/ToMathlib/Interval.lean

After discussion [on Zulip](https://leanprover.zulipchat.com/#narrow/channel/442935-Carleson/topic/Lemma.2010.2E1.2E2.20and.20Chapter.2010/near/506398730).
Will be used to fix a `sorry` in PR #261.
Before putting more work in proving Annulus versions, a first review of the Interval stuff would be appreciated to avoid rework later.
In particular I am not sure about the imports, and the proofs feel a bit long and clunky to me.

Some Interval results

---

Carleson/ToMathlib/Annulus.lean

Straightforward continuation of #273 applied to Annulus. With this, it's ready to resolve a sorry in #261.

Apply Interval results to Annulus

---

Carleson/ToMathlib/RealInterpolation.lean

The first commit is extracted from #209, the others may or may not be. Not exhaustive, but a start.

chore(RealInterpolation): clean-up

---

Carleson/ToMathlib/RealInterpolation.lean

Inspired by/extracted from #209. Also generalise one section where this is very easy.

chore(RealInterpolation): further clean-ups

---

Carleson/TwoSidedCarleson/WeakCalderonZygmund.lean

Don't have access to Lean atm. Feel free to fix the errors and merge.

add hypothesis stating 4 <= a in 10.2

---

Carleson/Classical/CarlesonOnTheRealLine.lean
Carleson/Defs.lean
Carleson/HolderVanDerCorput.lean
blueprint/src/chapter/main.tex

Also adapt the statement, the statement of Lemma 8.0.1 and the blueprint, assuming that the function is Hölder on `B(z, 2R)` instead of just `B (z, R)` as initially claimed: as discussed on Zulip, this is not enough to obtain the statements.

feat: Proposition 2.0.5

---

Carleson/ForestOperator/LargeSeparation.lean
Carleson/TileExistence.lean
Carleson/TileStructure.lean

Mostly, the defLemma linters, some unused haves and a tiny bit of formatting.

chore: fix some environment linters

---

Carleson/ToMathlib/ENorm.lean
Carleson/ToMathlib/HardyLittlewood.lean
Carleson/ToMathlib/Misc.lean
Carleson/ToMathlib/WeakType.lean

* prove some more ENNReal.toReal lemmas

move some lemmas away from WeakType

---

Carleson/Defs.lean
Carleson/ToMathlib/Misc.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean

One remaining `sorry` from lemma 10.1.2, turned out to be doable after all.
Maybe the ToMathlib result should have `fun_prop` as well; feel free to add that.

Prove `Measurable vol` (and `Measurable ball`)

---

Carleson/ToMathlib/RealInterpolation/Minkowski.lean

This generalises all lemmas to enorm classes which are possible now: the remainder requires generalising trunc and truncCompl, which is being worked on.
Depends on #326: merge that PR first, then rebase this one. (Combined CI for both shall suffice.)

chore(RealInterpolation/Minkowski): generalise a few lemmas to enorm

---

.github/workflows/push.yml
.github/workflows/push_pr.yml

For context, see this [zulip topic](https://leanprover.zulipchat.com/#narrow/channel/442935-Carleson/topic/Blueprint.20Lean.20links.20404'ed/near/516246582).

chore: fix cache step

---

Carleson/ToMathlib/HardyLittlewood.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean

[chore] Remaining PR comments 10.1.4

---

Carleson/Defs.lean
Carleson/ForestOperator/L2Estimate.lean
Carleson/Psi.lean

New substructure of ProofData

---

Carleson/TwoSidedCarleson/Basic.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean
blueprint/src/chapter/main.tex

Proof was straightforward.
I added `czoperator_sub` directly because it felt like the extra effort to state and prove linearity of `czoperator` was not worth it.

Lemma 10.1.5

---

Carleson/TwoSidedCarleson/NontangentialOperator.lean

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/channel/442935-Carleson/topic/HasBoundedStrongType.20.2F.20WeakType.20formalisation/with/519219963)

fix(NontangentialOperator): use HasBoundedStrongType

---

Carleson.lean
Carleson/ToMathlib/MeasureTheory/Measure/NNReal.lean

Add the natural pushforward measure in NNReal and ENNReal, and prove that it has the value you expect.

feat: measure on NNReal and ENNReal

---

Carleson/Antichain/AntichainOperator.lean
blueprint/src/chapter/main.tex

@mariainesdff fyi: I stated the last remaining lemma in chapter 6 so that we can claim we have stated all lemmas.

state last lemma, add two \proves commands

---

Carleson/ForestOperator/AlmostOrthogonality.lean
Carleson/ForestOperator/LargeSeparation.lean
Carleson/ToMathlib/BoundedCompactSupport.lean
Carleson/ToMathlib/Misc.lean

Fills the two sorry's introduced during the refactor.

finish the BoundedCompactSupport refactor

---

Carleson/ToMathlib/Data/ENNReal.lean

feat: add a few more lemmas to the finiteness tactic

---

Carleson/ForestOperator/L2Estimate.lean
Carleson/ToMathlib/BoundedFiniteSupport.lean
Carleson/ToMathlib/WeakType.lean
Carleson/TwoSidedCarleson/NontangentialOperator.lean

As dicussed on [Zulip](https://leanprover.zulipchat.com/#narrow/channel/442935-Carleson/topic/HasBoundedStrongType.20.2F.20WeakType.20formalisation/with/519348587).

Refactor BoundedWeakType/StrongType

---

Carleson/TileExistence.lean

Use positivity, gcongr and finiteness (as well as some local style tweaks).

chore(TileExistence): golf using tactics

---

Carleson/ForestOperator/AlmostOrthogonality.lean
Carleson/ForestOperator/Forests.lean
blueprint/src/chapter/main.tex

Includes a golfing of Lemma 7.4.4.

Lemma 7.7.3

---

Carleson/TwoSidedCarleson/NontangentialOperator.lean
blueprint/src/chapter/main.tex

With the additions to the blueprint, this was essentially trivial.

Task 158 (completes 10.1.6)

---

blueprint/src/chapter/main.tex

And now everything in the blueprint is green!

Mark Lemma 7.7.2 as completed

---

Carleson/ToMathlib/DoublingMeasure.lean
blueprint/src/chapter/main.tex

Sigma-finite is also redundant.

remove regularity assumption

---

blueprint/src/bibliography.bib
blueprint/src/chapter/main.tex
blueprint/src/print.tex

This adds an acknowledgement, fixes an affiliation and fixes some formatting issues in the bibliography.

add acknowledgement etc

---

Carleson/Classical/CarlesonHunt.lean
Carleson/Classical/ClassicalCarleson.lean
Carleson/Defs.lean
Carleson/MetricCarleson/Linearized.lean
Carleson/MetricCarleson/Main.lean
Carleson/Psi.lean

TODO: remove the first numbering level first...

chore: fix number references for new numbering
